# Generated by Django 4.2.3 on 2024-11-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PIZZA', max_length=200)),
                ('price', models.CharField(default='20.2', max_length=200)),
                ('servings', models.CharField(default='4', max_length=200)),
                ('preptime', models.CharField(default='50', max_length=200)),
                ('foodType', models.CharField(default='50', max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('banner', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
