# Generated by Django 4.2.3 on 2024-11-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOODS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='PIZZA', max_length=200, unique=True),
        ),
    ]
