# Generated by Django 4.2.3 on 2024-11-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOODS', '0002_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='banner',
            field=models.CharField(max_length=800),
        ),
    ]
